import React from "react";
import uuid from 'react-uuid';
import { useState, useEffect } from "react";
import Papa from "papaparse";

export default function CountryList({visible }) {
  const countries = [
    "Afganistan",
    "Afrika Erdiko Errepublika",
    "Aingira",
    "Г…land",
    "Albania",
    "Alemania",
    "Aljeria",
    "Ameriketako Estatu Batuak",
    "Ameriketako Estatu Batuetako Kanpoaldeko Uharte Txikiak",
    "Andorra",
    "Angola",
    "Antartika",
    "Antigua eta Barbuda",
    "Arabiar Emirerri Batuak",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamak",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belgika",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bielorrusia",
    "Birjina uharte amerikarrak",
    "Birjina uharte britainiarrak",
    "Boli Kosta",
    "Bolivia",
    "Bosnia-Herzegovina",
    "Botswana",
    "Bouvet uhartea",
    "Brasil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Christmas uhartea",
    "Cocos (Keeling) uharteak",
    "Cook uharteak",
    "Costa Rica",
    "CuraГ§ao",
    "Danimarka",
    "Djibuti",
    "Dominika",
    "Dominikar Errepublika",
    "Egipto",
    "Ekialdeko Timor",
    "Ekuador",
    "Ekuatore Ginea",
    "El Salvador",
    "Eritrea",
    "Erresuma Batua",
    "Errumania",
    "Errusia",
    "Eslovakia",
    "Eslovenia",
    "Espainia",
    "Estonia",
    "Etiopia",
    "Falklandak",
    "Faroe uharteak",
    "Fiji",
    "Filipinak",
    "Finlandia",
    "Frantzia",
    "Gabon",
    "Gambia",
    "Georgia",
    "Ghana",
    "Gibraltar",
    "Ginea",
    "Ginea Bissau",
    "Grenada",
    "Grezia",
    "Groenlandia",
    "Guadalupe",
    "Guam",
    "Guatemala",
    "Guernesey",
    "Guyana",
    "Guyana Frantsesa",
    "Haiti",
    "Heard eta McDonald uharteak",
    "Hego Korea",
    "Hego Sudan",
    "Hegoafrika",
    "Hegoaldeko Georgia eta Hegoaldeko Sandwich uharteak",
    "Hegoaldeko lurralde frantsesak",
    "Herbehereak",
    "Honduras",
    "Hong Kong Txinako AEB",
    "Hungaria",
    "India",
    "Indiako Ozeanoko lurralde britainiarra",
    "Indonesia",
    "Ipar Korea",
    "Ipar Mariana uharteak",
    "Ipar Mazedonia",
    "Irak",
    "Iran",
    "Irlanda",
    "Islandia",
    "Israel",
    "Italia",
    "Jamaika",
    "Japonia",
    "Jersey",
    "Jordania",
    "Kaiman uharteak",
    "Kaledonia Berria",
    "Kamerun",
    "Kanada",
    "Kanbodia",
    "Karibeko Herbehereak",
    "Kazakhstan",
    "Kenya",
    "Kirgizistan",
    "Kiribati",
    "Kolonbia",
    "Komoreak",
    "Kongo",
    "Kongoko Errepublika Demokratikoa",
    "Kroazia",
    "Kuba",
    "Kuwait",
    "Laos",
    "Lesotho",
    "Letonia",
    "Libano",
    "Liberia",
    "Libia",
    "Liechtenstein",
    "Lituania",
    "Luxenburgo",
    "Macau Txinako AEB",
    "Madagaskar",
    "Malawi",
    "Malaysia",
    "Maldivak",
    "Mali",
    "Malta",
    "Man uhartea",
    "Maroko",
    "Marshall Uharteak",
    "Martinika",
    "Mauritania",
    "Maurizio",
    "Mayotte",
    "Mendebaldeko Sahara",
    "Mexiko",
    "Mikronesia",
    "Moldavia",
    "Monako",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Mozambike",
    "Myanmar (Birmania)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Niger",
    "Nigeria",
    "Nikaragua",
    "Niue",
    "Norfolk uhartea",
    "Norvegia",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinar Lurralde Okupatuak",
    "Panama",
    "Papua Ginea Berria",
    "Paraguai",
    "Peru",
    "Pitcairn uharteak",
    "Polinesia Frantsesa",
    "Polonia",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Ruanda",
    "Saint BarthГ©lemy",
    "Saint Kitts eta Nevis",
    "Saint Vincent eta Grenadinak",
    "Saint-Pierre eta Mikelune",
    "Salomon Uharteak",
    "Samoa",
    "Samoa Estatubatuarra",
    "San Marino",
    "San Martin",
    "Santa Helena",
    "Santa Luzia",
    "Sao Tome eta Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelleak",
    "Sierra Leona",
    "Singapur",
    "Sint Maarten",
    "Siria",
    "Somalia",
    "Sri Lanka",
    "Sudan",
    "Suedia",
    "Suitza",
    "Surinam",
    "Svalbard eta Jan Mayen uharteak",
    "Swazilandia",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailandia",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad eta Tobago",
    "Tunisia",
    "Turk eta Caico uharteak",
    "Turkia",
    "Turkmenistan",
    "Tuvalu",
    "Txad",
    "Txekia",
    "Txile",
    "Txina",
    "Uganda",
    "Ukraina",
    "Uruguai",
    "Uzbekistan",
    "Vanuatu",
    "Vatikano Hiria",
    "Venezuela",
    "Vietnam",
    "Wallis eta Futuna",
    "Yemen",
    "Zambia",
    "Zeelanda Berria",
    "Zimbabwe",
    "Zipre",
  ];

  return (
    <div>
      <label className="CountryList" for="countries">
        {" "}
        <div className={visible? "fname":"invisible"}>
          Which country do you live in? <h className="RedStar">*</h>{" "}
        </div>
      </label>
      <select
        className="CountryList CountryListSelect"
        id="country"
        name="country"
      >
        {countries.map((element, index) => {
          return (
            <option
              className="CountryListSelect"
              
              key={uuid()}
              value={element}
            >
              {element}
            </option>
          );
        })}
        Country
      </select>
      Country
    </div>
  );
}
