import React from "react";

export default function newsPort() {
  const text = [
    "There’s something about the risk and reward inherent to motorcycling that attracts interesting–albeit disparate–personalities. From thrillseekers to commuters, to collectors and outlaws, these kindred spirits all have at least one thing in common: a need to be totally immersed in their transportation. This desire often manifests itself in their choice of motorcycle, as well as its appearance and performance. Rare is the ride whose owner hasn’t altered some aspect of a sufficiently functional and attractive vehicle.",
    "The fortunate among these enthusiasts magnify their obsession via unique aesthetics, enhanced performance, increased comfort, and yes… improved safety. ARCH Motorcycle was conceived as a one-stop destination for the most determined of these souls. The quest: to create a top-shelf, bespoke option for seekers of the ultimate motorcycle exercise. A consolidation of craftsmanship and cutting-edge technology which allows each owner the opportunity to influence the look and feel of their personal ARCH Motorcycle. Included with every ARCH delivered is the “esprit de corpse” of a diverse group of fascinating individuals, who share their passions for motorcycling and beyond, cultivated through exclusive owner events that combine motorcycling with culture, in unique and varied settings.",
    "The founding father of the ARCH Owners tribe is Vic Branstetter, a successful hospitality entrepreneur whose integrity permeates every room he enters. Vic is ARCH’s resident expert on aspirational vehicle ownership. When pushed to estimate how many bucket list vehicles he’s owned, his infectious smile tells the story better than any three-digit number could. Although he leans toward personal anonymity, serious SoCal gearheads have likely sifted through thick crowds to get a closer look at one of his new-in-country vehicles. Chances are, the rest of you have viewed his transportation options via reality TV, or seen his projects jumping from the covers of industry magazines. A perpetual early adopter in the exotic vehicle space, he embraces his addiction to the latest and greatest. “I’m not a collector,” Vic claims. “I’m an acquirer.” Like Hemingway in Africa, Vic seeks the thrill in acquisition of exotics. And like the rest of us, he likes to put his thumbprint on them. Actual thumbprints, though, are unacceptable in his world.",
    "Mr. Branstetter comes by his self-described “gearhead disorder” honestly. From humble beginnings in the heartland of Oklahoma, this son of a son of a mechanic spent the bulk of his youth engaged with his grandfather and father on various wheeled projects. Vic’s Dad, an airline mechanic by trade, was also an auto parts jobber for Edelbrock and Iskenderian. While his friends played with toys, Vic recalls stuffing manifolds and carburetors underneath his childhood bed. “From about 3 years old, I was my dad’s helper,” he says, fetching tools and providing an extra set of greasy hands. As an enthusiastic 5-year-old, he strapped on a mask and helped his father repaint the family’s ’49 Oldsmobile in their home garage. Before most could ride a bicycle, Vic was customizing his JC Higgins Freightliner. His future MO was apparent: completely deconstructing many of his rides within days of receiving them. His father enabled young Vic’s affliction, by keeping a steady stream of projects in front of him. Countless bicycles, minibikes, and go-karts were subject to his scrutiny, spawning a lifelong bond between the two of them.",

    "As Vic matured, his attention evolved to more ambitious and expensive vehicles. Upon graduation from college, his father’s advice to seek a lucrative job that would bankroll his hobbies, rather than a fun one inside the automotive industry, made sense. His choice to follow some friends into the restaurant business apparently missed the mark with the elder Branstetter. “Oh great, now you’re selling hamburgers?” he asked. Undeterred, Vic put his head down and applied his laser focus to his new profession. The one that would ultimately allow him to repay his parents with dream cars and a new home.",
    "Upon the successful launch and growth of the Houston’s chain of eateries (now known as Hillstone Restaurant Group) Vic found himself headquartered in Atlanta, in charge of operations at multiple locations in the region. He admits his decision to purchase a plane and fly himself between the stores was short-sighted. Especially, since the ambitious scaling of their restaurant business was quickly testing the limits of his equipment and skill set. He decided to go back to flying commercial and focus on safer, earthbound hobbies. This enabled a nautical fixation that involved multiple off-shore cigarette boats, and ended with a festive (read expensive) foray into yacht ownership. With Houston’s blowing up nationwide, the West Coast beckoned, and Vic found his new forever home in Southern California.",
    "It was in Los Angeles where Vic’s motorcycle addiction blossomed. Sure, he had owned plenty of bikes since his days in Oklahoma, but now, it actually made sense to ride a motorcycle. Perfect, year-round weather with empty and endless canyon roads, accessible via legal lane-splitting. This concept may be polarizing in the national discussion, but SoCal motorcyclists know it’s the key to survival on their roads. In addition, the weather and canyons are a boon for exotic car owners who unveil their gems on weekends, to test g-forces en route to grab an $8 coffee in Malibu. Vic was primed for this scene, and ready to make his statement.",
    "A seasoned Ferrari and Porsche fanatic from his days in Atlanta, Vic secured first right of refusal status with the sales managers of these iconic marques. Since collecting is not the ultimate goal, he is more often motivated by game-changing performance updates or boundary-pushing technology breakthroughs. “I love to drive the newest and best on the market, no matter the brand,” he says. But sometimes,“all it takes is a stunning paint job.” Orange is his preferred color. For the last 10 years, or so, Vic has housed his stable of vehicles in a local SoCal airport hangar. It’s convenient, and safe enough that he counts several A-list celebrities as his neighbors. The eclectic inventory he retains is a people magnet, and fluid, to say the least. Vic prefers it that way. One consistent occupant, though, is his current helicopter. Vic’s pilot itch resurfaced a few years back while celebrating the 4th of July in Miami, with some of his LA motorcycle crew. Most were already pilots, and all shared his interest in learning to fly helicopters. Upon return, they met with veteran instructor Ken Obi to flesh out the opportunity. Ken explained that piloting a helicopter is similar to motorcycling in that it requires the use of both hands and feet. He said, “if you are proficient on a motorcycle, I can teach you to fly a helicopter, if not..forget it.” Vic immediately dedicated several hours a day, Monday through Friday, to the endeavor, and acquired his helicopter license in only three months time. His buddies followed suit, but eventually returned to airplanes, leaving Vic as the primary helicopter pilot of the group. He’s attracted to the “Imax Theater” aspect of helicopters, over the utility of airplanes. A similarity which seems applicable in the motorcycles vs cars debate.",

    "Since selling his stake in Houston’s 15 years ago, Vic has shifted his professional focus to the Branstetter Group, a premium hospitality consulting company he launched with other industry experts. He enjoys the unique and varied challenges inherent to the consulting industry, which also happens to satisfy his entrepreneurial drive. Their primary focus is substantial restaurant projects, but broadens on occasion to include motorsports, as well as other industries.",
    "On a personal note, Vic found the perfect soulmate for his ambitious lifestyle in his lovely wife Kelli. Beyond their elegant Pacific Palisades estate, Kelli lists philanthropy and animal rescue among her many passions. Their extended “furry” family is known to grow with little notice, as she is famously generous in her concern for the four-legged among us. The current beneficiaries include four French bulldogs, a Staffordshire bull terrier, a papillon, a chihuahua mix and a Sphynx, hairless cat. This year’s Branstetter Christmas card photo session will surely be one for the ages.",
    "Vic Branstetter was the ideal first client for our fledgling motorcycle company, committing to the initial production model months before it rolled off the hand-assembly line. He was well aware of Gard’s reputation for attention to detail, and was anxious to witness the transformation from genre-bending prototype to street legal production model. The first generation KRGT-1 checked virtually every box Branstetter looks for in his acquisitions. Since his initial purchase in 2015, Vic has added two more ARCH Motorcycles to his fleet. He claims the ARCH KRGT-1 is the ultimate lane-splitting canyon carver, with the bonus of being a true American exotic. ARCH Motorcycle is proud to claim Vic Branstetter as a friend, and founding member of our revered enthusiast family.",
  ];

  roadMap = [
    ["text", 0],
    ["text", 1],
    ["text", 2],
    ["text", 3],
    ["imgs", 0],
    ["text", 4],
    ["text", 5],
    ["text", 6],
    ["text", 7],
    ["imgs", 1],
    ["text", 8],
    ["imgs", 2],
    ["text", 9],
    ["text", 10],
    ["text", 11],
    ["imgs", 2],
  ];

  const header = [
    "Owner Profile:",
    "Vic Branstetter",
    "By Keith Oliver",
    "March 11, 2021",
  ];
  return <div></div>;
}
